---
- block:
    - name: Ensure procps is installed.
      ansible.builtin.package:
        name: "{{ procps_package }}"
        state: present

    - name: Ensure br_netfilter is enabled.
      community.general.modprobe:
        name: "{{ item }}"
        state: present
        persistent: present
      loop:
        - overlay
        - br_netfilter

    - name: Let iptables see bridged traffic.
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward
  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10
